// Code generated by hjing. DO NOT EDIT.

package main

import (
	"github.com/jkkkls/hjing/utils"
	"github.com/jkkkls/hjing/rpc"

	//end import
)

func main() {
	utils.NewApp("{{appName}}.yaml").WithRegister(func(app *utils.App) error {
		//
		//end register
		return nil
	}).Run()
}
