//Code generated by xlsx2proto. DO NOT EDIT.

package examples

// SdkConfig SDK配置
type SdkConfig struct {
	Id          int64   `json:"id,omitempty"`           //ID
	Channels    []int64 `json:"channels,omitempty"`     //渠道ids
	TaskId      int64   `json:"task_id,omitempty"`      //任务id
	SdkId       int64   `json:"sdk_id,omitempty"`       //SDK_Id
	Priority    int64   `json:"priority,omitempty"`     //视频优先度
	VideoId     string  `json:"video_id,omitempty"`     //视频广告Id
	VideoLimit  int64   `json:"video_limit,omitempty"`  //视频广告次数限制
	CoolTime    int64   `json:"cool_time,omitempty"`    //冷却时间
	Day         []int64 `json:"day,omitempty"`          //注册天数
	SplashId    string  `json:"splash_id,omitempty"`    //开屏广告Id
	SplashLimit int64   `json:"splash_limit,omitempty"` //开屏次数分配
	Bak         string  `json:"bak,omitempty"`          //备注
}

// GroupConfig 分群配置
type GroupConfig struct {
	Id                int64      `json:"id,omitempty"`                  //ID
	StartRegisterTime string     `json:"start_register_time,omitempty"` //注册开始时间
	EndRegisterTime   string     `json:"end_register_time,omitempty"`   //注册结束时间
	Channel           []int64    `json:"channel,omitempty"`             //渠道屏蔽
	RegVersion        [][]string `json:"reg_version,omitempty"`         //注册版本号
	Weight            int64      `json:"weight,omitempty"`              //取模结果值
	AbValue           string     `json:"ab_value,omitempty"`            //结果
}

type Configs struct {
	SdkConfig   []SdkConfig   `json:"sdk_config,omitempty"`   //SDK配置
	GroupConfig []GroupConfig `json:"group_config,omitempty"` //分群配置
}
