// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0-devel
// 	protoc        v4.25.3
// source: pb/interface.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 接口命令
type InterfaceCmd int32

const (
	InterfaceCmd_InterfaceCmd_Begin InterfaceCmd = 0
)

// Enum value maps for InterfaceCmd.
var (
	InterfaceCmd_name = map[int32]string{
		0: "InterfaceCmd_Begin",
	}
	InterfaceCmd_value = map[string]int32{
		"InterfaceCmd_Begin": 0,
	}
)

func (x InterfaceCmd) Enum() *InterfaceCmd {
	p := new(InterfaceCmd)
	*p = x
	return p
}

func (x InterfaceCmd) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InterfaceCmd) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_interface_proto_enumTypes[0].Descriptor()
}

func (InterfaceCmd) Type() protoreflect.EnumType {
	return &file_pb_interface_proto_enumTypes[0]
}

func (x InterfaceCmd) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InterfaceCmd.Descriptor instead.
func (InterfaceCmd) EnumDescriptor() ([]byte, []int) {
	return file_pb_interface_proto_rawDescGZIP(), []int{0}
}

var File_pb_interface_proto protoreflect.FileDescriptor

var file_pb_interface_proto_rawDesc = []byte{
	0x0a, 0x12, 0x70, 0x62, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2a, 0x26, 0x0a, 0x0c,
	0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x43, 0x6d, 0x64, 0x12, 0x16, 0x0a, 0x12,
	0x49, 0x6e, 0x74, 0x65, 0x72, 0x66, 0x61, 0x63, 0x65, 0x43, 0x6d, 0x64, 0x5f, 0x42, 0x65, 0x67,
	0x69, 0x6e, 0x10, 0x00, 0x42, 0x1f, 0x5a, 0x1d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x6a, 0x6b, 0x6b, 0x6b, 0x6c, 0x73, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x61,
	0x70, 0x70, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_interface_proto_rawDescOnce sync.Once
	file_pb_interface_proto_rawDescData = file_pb_interface_proto_rawDesc
)

func file_pb_interface_proto_rawDescGZIP() []byte {
	file_pb_interface_proto_rawDescOnce.Do(func() {
		file_pb_interface_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_interface_proto_rawDescData)
	})
	return file_pb_interface_proto_rawDescData
}

var file_pb_interface_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pb_interface_proto_goTypes = []interface{}{
	(InterfaceCmd)(0), // 0: common.InterfaceCmd
}
var file_pb_interface_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_interface_proto_init() }
func file_pb_interface_proto_init() {
	if File_pb_interface_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_interface_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_interface_proto_goTypes,
		DependencyIndexes: file_pb_interface_proto_depIdxs,
		EnumInfos:         file_pb_interface_proto_enumTypes,
	}.Build()
	File_pb_interface_proto = out.File
	file_pb_interface_proto_rawDesc = nil
	file_pb_interface_proto_goTypes = nil
	file_pb_interface_proto_depIdxs = nil
}
